# Generated by Django 4.2.27 on 2025-12-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('rented', 'En uso'), ('maintenance', 'Mantenimiento')], default='available', max_length=12, verbose_name='Estado')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Precio por día', max_digits=10, verbose_name='Tarifa diaria')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('booked', 'Reservado'), ('in_progress', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='booked', max_length=12, verbose_name='Estado')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Costo total')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.car', verbose_name='Vehículo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_date'],
            },
        ),
    ]
